apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: development
  labels:
    app: iot-gitlab
spec:
  sourceRepos:
    - http://HOST_IP/root/*
  destinations:
    - namespace: gitlab
      server: https://kubernetes.default.svc
  orphanedResources:
    warn: false