# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX="bento/ubuntu-22.04"

PROVIDER="virtualbox"

CPU = 2
MEM = 8192

CONTROLLER_MACHINE_NAME="inceptionOfThings"
CONTROLLER_NAME="inceptionOfThings"

Vagrant.configure("2") do |config|

  config.vm.box = BOX

  config.vm.provider PROVIDER do |vb|
    vb.memory = MEM
    vb.cpus = CPU
    vb.gui = true
  end

  config.vm.network :forwarded_port, guest: 22, host: 3200, id: 'ssh'

  config.vm.define CONTROLLER_NAME do |ctl|
    ctl.vm.hostname = CONTROLLER_NAME
    ctl.vm.provider PROVIDER do |vb|
      vb.name = CONTROLLER_MACHINE_NAME
      vb.customize ['modifyvm', :id, '--nested-hw-virt', 'on']
    end
    ctl.vm.provision :shell, path: "./setup_vm.sh"
  end
end
