apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: development
  labels:
    app: iot-argocd
spec:
  sourceRepos:
    - https://github.com/keonwoo98/keokim-argocd.git
  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc
  orphanedResources:
    warn: false