# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-16.04"
  config.vm.box_url = "https://vagrantcloud.com/bento/boxes/ubuntu-16.04/versions/202212.11.0/providers/virtualbox/unknown/vagrant.box"

  config.vm.define "jaemjungS" do |control|
    control.vm.hostname = "jaemjungS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = "512"
      vb.customize ["modifyvm", :id, "--name", "jaemjungS"]
    end
    config.vm.provision :shell, path: "setup_server.sh"
  end

  # config.vm.define "jaemjungSW" do |control|
  #   control.vm.hostname = "jaemjungSW"
  #   control.vm.network "private_network", ip: "192.168.56.111"
  #   control.vm.provider "virtualbox" do |vb|
  #     vb.cpus = 1
  #     vb.memory = "512"
  #     vb.customize ["modifyvm", :id, "--name", "jaemjungSW"]
  #   end
  # end
end
