# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX="bento/ubuntu-22.04"

PROVIDER="virtualbox"

CPU = 1
MEM = 512

CONTROLLER_MACHINE_NAME="jaemjung"
CONTROLLER_NAME="jaemjungS"
CONTROLLER_IP="192.168.56.110"

WORKER_MACHINE_NAME="keokim"
WORKER_NAME="keokimSW"
WORKER_IP="192.168.56.111"

Vagrant.configure("2") do |config|

  config.vm.box = BOX

  config.vm.provider PROVIDER do |vb|
    vb.memory = MEM
    vb.cpus = CPU
  end

  config.vm.define CONTROLLER_NAME do |ctl|
    ctl.vm.hostname = CONTROLLER_NAME
    ctl.vm.network "private_network", ip: CONTROLLER_IP
    ctl.vm.provider PROVIDER do |vb|
      vb.name = CONTROLLER_MACHINE_NAME
    end
    ctl.vm.provision :shell, path: "scripts/setup_server.sh"
  end

  config.vm.define WORKER_NAME do |wrk|
    wrk.vm.hostname = WORKER_NAME
    wrk.vm.network "private_network", ip: WORKER_IP
    wrk.vm.provider PROVIDER do |vb|
      vb.name = WORKER_MACHINE_NAME
    end
    wrk.vm.provision :shell, path: "scripts/setup_agent.sh"
  end
end
