# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX="bento/ubuntu-20.04"

PROVIDER="virtualbox"

CPU = 2
MEM = 4096

CONTROLLER_MACHINE_NAME="jaemjungS"
CONTROLLER_NAME="jaemjungS"
CONTROLLER_IP="192.168.56.110"

Vagrant.configure("2") do |config|

  config.vm.box = BOX

  config.vm.provider PROVIDER do |vb|
    vb.memory = MEM
    vb.cpus = CPU
    vb.gui = true
  end

  config.vm.define CONTROLLER_NAME do |ctl|
    ctl.vm.hostname = CONTROLLER_NAME
    ctl.vm.network "private_network", ip: CONTROLLER_IP
    ctl.vm.provider PROVIDER do |vb|
      vb.name = CONTROLLER_MACHINE_NAME
    end
    ctl.vm.provision :shell, path: "scripts/install_gui.sh"
  end
end
